### ISSUE TITLE
Login page does not display errors

### ISSUE THREAD

**Issue by sman591** [codeRIT/hackathon_manager#28]
_From @sman591 on January 11, 2015 7:29_

If the user submits a blank login form, or submits incorrect information, an error message should display. However, this is not the case.

Both `devise_error_messages!` and `f.error_notification` return nothing, and `resource.errors.empty?` is true.

_Copied from original issue: codeRIT/brickhack.io#57_

**Comment by dquach217** [comment]
Where exactly is the validation being done?

**Comment by sman591** [comment]
The validation is performed by Devise - I think here: https://github.com/plataformatec/devise/blob/88724e10adaf9ffd1d8dbfbaadda2b9d40de756a/lib/devise/strategies/database_authenticatable.rb

So my guess is it fails here, but somewhere after the validation fails the error message gets swallowed...

**Comment by sman591** [comment]
(we enable `:database_authenticatable` here: https://github.com/codeRIT/hackathon_manager/blob/master/app/models/user.rb#L2)

**Comment by sman591** [comment]
_Finally_ figured this out. Error messages are being stored to `flash[:alert]` instead of `flash[:notice]` 🤦‍♂
