### ISSUE TITLE
Use official MLH school list

### ISSUE THREAD

**Issue by sman591** [codeRIT/hackathon_manager#41]
MLH maintains a manually-verified list of schools, available at https://github.com/MLH/mlh-policies/blob/master/schools.csv

This list *doesn't* include city/state information, which is needed to generate the applicant map. Could probably use our existing school data to add to MLH's list where possible, and leave other school's city/state blank for now.

**Comment by dquach217** [comment]
@sman591 seems like their list of schools are lacking as compared to our list, are you sure you want to either merge them or use MLH and just add the addresses?

**Comment by sman591** [comment]
Oh, didn’t know it was particularly lacking. If that’s the case we shouldn’t use it, but I thought this was the list MLH provided most hackathons?

**Comment by dquach217** [comment]
could be the case, but the list we provide is all schools even those that have not participated in a hackathon

**Comment by dquach217** [comment]
@sman591 should we close this ticket then?

**Comment by sman591** [comment]
Yeah
