### ISSUE TITLE
Show exact school locations on interactive map

### ISSUE THREAD

**Issue by sman591** [codeRIT/hackathon_manager#58]
Right now, we display a high-level overview of where applicants are applying from, as well as the quantity.

However, if this were an interactive map (e.g. Google Maps overlay), this map could be zoomed in to see:
* Exact location of applicants for planning bus routes
* Visibility into which schools have a bus list active for them

For example: University Abc has a bus, but just down the road is another school with 5 applicants. Right now it's hard for someone to connect the dots, but if this was more precisely visible on a map, someone could see the close distance and be sure to reach out to those students about the bus.

**Comment by membrq** [comment]
Can I claim?

**Comment by sman591** [comment]
@membrq This is a relatively large feature that ties into a lot of how this Ruby gem works. If you'd like to take this, it'd be great to have some discussion on how it's going to work. Have you worked with a maps API like Google Maps before?

**Comment by sman591** [comment]
Merging into #83
