### ISSUE TITLE
Denied status shows thank you message

### ISSUE THREAD

**Issue by sman591** [codeRIT/hackathon_manager#62]
<img width="762" alt="screenshot 2018-01-08 16 18 33" src="https://user-images.githubusercontent.com/1441807/34692865-9ee96680-f48f-11e7-9342-165d9d6d9d0d.png">

**Comment by membrq** [comment]
Can I take this?

**Comment by sman591** [comment]
@membrq I'd prefer to take this one myself if that's ok - it deals with a rather important decision tree of handling acceptance statuses

**Comment by membrq** [comment]
Not a problem!
