### ISSUE TITLE
Flashes show up twice on questionnaire page

### ISSUE THREAD

**Issue by sman591** [codeRIT/hackathon_manager#63]
<img width="1102" alt="screenshot 2018-01-08 16 46 48" src="https://user-images.githubusercontent.com/1441807/34694001-90049834-f493-11e7-9e89-74bd154d66e4.png">

**Comment by membrq** [comment]
Can I claim?

**Comment by sman591** [comment]
@membrq Sure! Feel free to submit a PR and reference this issue. Can post here if you have any questions.
